### ISSUE TITLE
Install fails on Python 3.7

### ISSUE THREAD

**Issue by Sharparam** [codejamninja/dotstow#2]
Installing dotstow with pip works fine on Python 3.6.8, but seems to break on Python 3.7.3.

See [the log from running `pip install dotstow`](https://gist.github.com/Sharparam/ebf1dcc2a29c48749d97f0a3c2fdf04c).

## System details

Python 3.7.3 installed using pyenv.

Distro: Antergos (Arch) 64-bit

```
$ uname -a
Linux sharpx260 5.1.9-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 11 16:18:09 UTC 2019 x86_64 GNU/Linux
```

**Comment by clayrisser** [comment]
Ok, I will take a more detailed look at this when I get around to it.

**Comment by FDiskas** [comment]
```
sudo npm install -g dotstow
 alias hint: _ npm install -g dotstow
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/dotstow -> /usr/local/lib/node_modules/dotstow/bin.js

> nodegit@0.26.2 install /usr/local/lib/node_modules/dotstow/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.26.2 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build'
gyp

ERR! configure error
gyp
ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build'
gyp
ERR! System Darwin 19.0.0
gyp
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp
ERR! cwd /usr/local/lib/node_modules/dotstow/node_modules/nodegit
gyp ERR!
node -v v10.16.3
gyp ERR!
node-gyp -v v3.8.0
gyp ERR!
not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/dotstow/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR!
stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp
ERR! System Darwin 19.0.0
node-pre-gyp ERR!
command "/usr/local/bin/node" "/usr/local/lib/node_modules/dotstow/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/usr/local/lib/node_modules/dotstow/node_modules/nodegit
node-pre-gyp ERR! node -v
v10.16.3
node-pre-gyp

ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/dotstow/node_modules/nodegit/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.26.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.26.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2019-12-03T09_04_50_414Z-debug.log
```
```
Darwin FDisk.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

**Comment by clayrisser** [comment]
That's a file permission error. It means npm does not have execute permission for that folder. I find that odd because you are using sudo. Some suggestions . . .

1. You could try reinstalling NodeJS
2. You could install [nvm](https://github.com/nvm-sh/nvm) and then install `dotstow` without using `sudo`.

Personally I recommend the second approach, because you really shouldn't be giving npm scripts sudo access anyways (what if an npm module had malicious code in).

**Comment by clayrisser** [comment]
Not an issue anymore now that it's rewritten in POSIX shell.
